# Generated by Django 5.2.14 on 2026-05-22 04:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="application",
            name="recommendation_reasoning",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="recommended_program",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subjectmatch",
            name="matching_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subjectmatch",
            name="source",
            field=models.CharField(
                choices=[
                    ("tor", "TOR"),
                    ("work_experience", "Work Experience"),
                    ("certification", "Certification"),
                ],
                default="tor",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="subjectmatch",
            name="tor_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.torsubject",
            ),
        ),
        migrations.CreateModel(
            name="ApplicantDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("tor", "Transcript of Records"),
                            ("psa", "PSA Birth Certificate"),
                            ("job_description", "Job Description"),
                            ("certificate", "Certificate"),
                            ("resume", "Resume"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.IntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ocr_raw", models.TextField(blank=True)),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.application",
                    ),
                ),
            ],
            options={
                "db_table": "applicant_documents",
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("years", models.FloatField(default=0)),
                ("job_description", models.TextField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="core.application",
                    ),
                ),
            ],
            options={
                "db_table": "work_experiences",
            },
        ),
        migrations.AddField(
            model_name="subjectmatch",
            name="work_experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.workexperience",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectmatch",
            index=models.Index(fields=["source"], name="subject_mat_source_41158c_idx"),
        ),
        migrations.AddIndex(
            model_name="applicantdocument",
            index=models.Index(
                fields=["application", "document_type"],
                name="applicant_d_applica_775c45_idx",
            ),
        ),
    ]
