# Generated by Django 5.2.14 on 2026-09-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_address_application_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torsubject',
            name='school_year',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='torsubject',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='torsubject',
            name='term_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='torsubject',
            name='year_level',
            field=models.IntegerField(default=1),
        ),
    ]
